apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    apps: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ghcr.io/wer153/account:main
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
